# Generated by Django 5.1.6 on 2025-02-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_fleet_alter_stockmovement_vehicle_delete_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='current_location_checkpoint',
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='source',
        ),
        migrations.CreateModel(
            name='FleetMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(auto_now=True)),
                ('departure_time', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('current_location_checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='inventory.warehouse')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='inventory.warehouse')),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fleet')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='inventory.warehouse')),
            ],
        ),
    ]
