# Generated by Django 5.1.6 on 2025-02-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_fleet_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='batch_no',
            field=models.CharField(default='no_assign_0000', max_length=100),
        ),
    ]
