# Generated by Django 5.1.6 on 2025-02-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockmovement_batch_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseemployee',
            old_name='employee_id',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='warehouseemployee',
            old_name='user',
            new_name='employee',
        ),
        migrations.AlterUniqueTogether(
            name='warehouseemployee',
            unique_together={('emp_id', 'warehouse')},
        ),
    ]
