# Generated by Django 5.1.6 on 2025-02-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_employee_id_warehouseemployee_emp_id_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouseemployee',
            unique_together={('employee', 'warehouse')},
        ),
        migrations.RemoveField(
            model_name='warehouseemployee',
            name='emp_id',
        ),
    ]
