# Generated by Django 5.1.6 on 2025-02-17 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_warehouseemployee_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleet',
            old_name='plate_number',
            new_name='fleet_code',
        ),
    ]
