# Generated by Django 5.1.6 on 2025-02-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_plate_number_fleet_fleet_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetmovement',
            name='current_location_checkpoint',
            field=models.TextField(),
        ),
    ]
