# Generated by Django 5.1.6 on 2025-02-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_fleetmovement_current_location_checkpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetmovement',
            name='current_location_checkpoint',
            field=models.TextField(blank=True),
        ),
    ]
