# Generated by Django 5.1.6 on 2025-02-17 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_fleetmovement_current_location_checkpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetmovement',
            name='fleet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.fleet'),
        ),
    ]
