# Generated by Django 5.1.6 on 2025-02-17 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_fleetmovement_fleet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
