# Generated by Django 5.1.6 on 2025-02-17 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetmovement',
            name='fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fleet'),
        ),
    ]
