# Generated by Django 5.1.6 on 2025-02-17 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_stockproductqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockproductqty'),
        ),
    ]
