# Generated by Django 5.1.6 on 2025-02-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_rename_vehicle_stockmovement_fleet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_threshold',
            field=models.IntegerField(default=0),
        ),
    ]
