# Generated by Django 5.1.6 on 2025-03-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_product_minimum_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='current_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
