# Generated by Django 5.1.6 on 2025-03-02 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_warehouse_current_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='movement_type',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_warehouse', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_warehouse', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='threshold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
