# Generated by Django 5.1.6 on 2025-03-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_stockmovement_movement_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_threshold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_company',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
