# Generated by Django 5.1.6 on 2025-03-02 17:00

import django.db.models.deletion
import django.utils.timezone
import inventory.models.fleet_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_product_minimum_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='source',
        ),
        migrations.AddField(
            model_name='fleetmovement',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockproductqty',
            name='batch_no',
            field=models.CharField(default='no_assign_0000', max_length=100),
        ),
        migrations.AddField(
            model_name='stockproductqty',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockproductqty',
            name='manufacture_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fleetmovement',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fleetmovement',
            name='departure_time',
            field=models.DateTimeField(default=inventory.models.fleet_models.default_departure_time),
        ),
        migrations.AlterField(
            model_name='fleetmovement',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_warehouse', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='fleetmovement',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_warehouse', to='inventory.warehouse'),
        ),
    ]
