# Generated by Django 5.1.6 on 2025-03-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_stockmovement_batch_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
