# Generated by Django 5.1.6 on 2025-03-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_warehouse_address_alter_warehouse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
